### ISSUE TITLE
Controllers written in Coffeescript?

### ISSUE THREAD

**Issue by Be-brand** [hotwired/stimulus-rails#100]
I'm fairly new to Rails, so I may just be missing something stupid. Using import maps, how can I write controllers in coffeescript?

I've installed the `coffee-rails` gem and set up a controller, but it seems that Stimulus just won't load the controller from this line `eagerLoadControllersFrom("controllers", application)`.

I'm certain this is a problem with Coffeescript because manually compiling the Coffeescript and putting the output in a plain JS controller side-by-side with the Coffeescript controller works perfectly; the JS controller hooks up to my DOM element, the Coffeescript controller simply doesn't execute.

Here's my repo demonstrating this (ignore everything in `/lib`): https://github.com/Be-brand/game-of-life

**Comment by dhh** [comment]
If you're doing any form of dynamic transpiling, you're not going to be able to use import maps. This approach is specifically for plain JavaScript controllers. But since ES6, I don't think you're giving up anything of great value forgoing coffee script.
