### ISSUE TITLE
Failing to register controllers does not bubble the error to handleError

### ISSUE THREAD

**Issue by crohr** [hotwired/stimulus-rails#102]
Whenever a controller fails to register (for instance if a `targetNameConnected()` method throws an error), stimulus will catch the error and display a console message. However that means we can never be alerted of that error, because it doesn't bubble the error to `application.handleError`, which I believe is the hook point to setup exception monitoring (appsignal, etc.)

Is it by design, or are you open to a fix?

https://github.com/hotwired/stimulus-rails/blob/7e0150bc2f30f8443c8bfdbfdd508c2eea4427e7/app/assets/javascripts/stimulus-loading.js#L27

**Comment by dhh** [comment]
Not by design. Would be good with a fix 👍

**Comment by stefannibrasil** [comment]
Hi! I ran into this issue recently and opened a PR to fix this 🤞🏼

**Comment by crohr** [comment]
Thanks @stefannibrasil, totally forgot to upstream the fix. Glad to see it merged!
