### ISSUE TITLE
manifest:update configuration for controller segmentation

### ISSUE THREAD

**Issue by tenpaiyomi** [hotwired/stimulus-rails#105]
I looked through the [manifest.rb](https://github.com/hotwired/stimulus-rails/blob/main/lib/stimulus/manifest.rb) and noted that there is only a single flow of logic for the creation of the manifest for controllers.  I actually had 2 separate questions here for this.

1. I have what are basically 3 sections of my application, the homepage, the app UI itself for a logged in user, and then the admin backend.  Ideally, in my mind, it would make sense to keep the controllers for these separated out and only load what is necessary for each, so I've been keeping them logically separated within the `controllers` folder:

    - `controllers/admin/*_controller.js`
    - `controllers/app/*_controller.js`
    - `controllers/homepage/*_controller.js`
  
    Just given how `stimulus-rails` and the manifest works, is this a _wrong_ approach?  Is the tradeoff of separation of the JS not enough of a benefit versus just loading all of the controllers at once?

2. If the answer to the above is that there is a benefit, are there any plans (or aversion to a PR) for allowing for the manifest update task to know, either via an argument or configuration, that certain folder(s) should be delegated out to their own root controller files?

A quick 30s brainstorming session gave me the rough idea of something such as an optional file within the `config` folder, `stimulus.yml` with a format such as:

```yaml
admin:
  - admin
  - foo
app:
homepage:
```

Such that when `rails stimulus:manifest:update` is run, it would check for the configuration file.  If it doesn't exist, it would work as normal, but if it does exist it would work such that (in the example of the above) it would generate the following:

`admin.js`
```
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__BarController from "./admin/some_controller.js"
application.register("admin--bar", Admin__BarController);

import Foo__BazController from "./foo/bar_controller.js"
application.register("foo--bar", Foo__BarController);
```

`app.js`
```
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import App__FeatureController from "./app/feature_controller.js"
application.register("app--feature", App__FeatureController);
```

`homepage.js`
```
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Homepage__FeatureController from "./homepage/feature_controller.js"
application.register("homepage--feature", Homepage__FeatureController);
```

`index.js`
```
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SharedFeatureController from "./shared_feature_controller.js"
application.register("shared-feature", SharedFeatureController);
```

Presumably the `stimulus.yml` parsing would need to be intelligent enough to raise an error in the case that `application` or `index` were passed since those are reserved, but that wouldn't be terribly difficult.

**Comment by dhh** [comment]
`stimulus:manifest:update` is just a nice to have for the most common case. You don't actually need to use/run it. You can either maintain these files directly, or you can overwrite that task (or create a new one) with more sophisticated behavior. Not keen to add the default complexity of a yml controlled config here.
