### ISSUE TITLE
Browser Back button is not working for some feature in stimulus 

### ISSUE THREAD

**Issue by RabeyaMuna** [hotwired/stimulus-rails#110]
I have created an website where we use stimulus in frontend part. No customer routes has been used there and turbo has been used in the webpage.
 This is the website:

https://food.store.biz.selise.tech

For product detail the issue is happening.

How to resolve that issue.

Code is given in the issue 

https://github.com/hotwired/stimulus/issues/589

**Comment by dhh** [comment]
The original issue raised in the Stimulus repo covers this, so I don't think we need another issue open for it. Also, highly unlikely that Stimulus is related to the back button issue in any case imo.

**Comment by RabeyaMuna** [comment]
Sorry, which issue you are talking about?

**Comment by RabeyaMuna** [comment]
This issue is raised again as no one has able to give a proper answer regarding this?
