### ISSUE TITLE
Debugging `Failed to auto-load controller` ... `Unable to resolve specifier`

### ISSUE THREAD

**Issue by turgs** [hotwired/stimulus-rails#118]
What could be the cause of the "unable to resolve specifier" errors? Does anyone have any advice how I can debug or what to try? 

The failure is occuring here https://github.com/hotwired/stimulus-rails/blob/498902a3687d32bd6589f7d3c7e7d72eabd822c0/app/assets/javascripts/stimulus-loading.js#L69-L71 but that's just passing-on the true error.

```
Failed to autoload controller: reveal Error: Unable to resolve specifier 'controllers/reveal_controller' imported from http://my.127-0-0-1.nip.io/assets/stimulus-loading-8ade71066f3152594b77e21595ddd0839ecb40ba.js
```

That controller does exist

**app/javascript/controllers/reveal_controller.js**

```js
import ApplicationController from "controllers/application_controller"

export default class extends ApplicationController {
  static targets = [ "toggleable" ];
  static classes = [ "hidden" ];

  toggle() {
    console.log('boomshakalaka')
    this.toggleableTargets.forEach(element => {
      element.classList.toggle('hidden')
    });
  }

  show() {
    this.toggleableTargets.forEach(element => {
      element.classList.remove(this.toggleClass)
    })
  }

  hide() {
    this.toggleableTargets.forEach(element => {
      element.classList.add(this.toggleClass)
    })
  }
}
```

I'm using Rails 7, Hotwire, Propshaft.

Gemfile.lock says
- stimulus-rails (1.2.1)
- propshaft (0.7.0)
- rails (7.0.4.3)
- importmap-rails (1.1.5)

I cannot figure out why the error is appearing, yet the controller still seems to function fine.

**config/importmap.rb**

```rb
# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true

pin "date-fns",   to: "https://ga.jspm.io/npm:date-fns@2.28.0/esm/index.js"
pin "flatpickr",  to: "https://ga.jspm.io/npm:flatpickr@4.6.10/dist/flatpickr.min.js"

pin_all_from "app/components"
pin_all_from "app/javascript/controllers", under: "controllers"
```

**app/javascript/controllers/index.js**

```js
// Import and register all your controllers from the importmap under controllers/*

import { application } from "controllers/application"

// Eager load all controllers defined in the import map under controllers/**/*_controller
// import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
// eagerLoadControllersFrom("controllers", application)

// Lazy load controllers as they appear in the DOM (remember not to preload controllers in import map!)
import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"
lazyLoadControllersFrom("controllers", application)
```

**app/javascript/controllers/application.js**

```js
import { Application } from "@hotwired/stimulus"

const application = Application.start()

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
```

I tried commenting out `pin "@hotwired/stimulus-loading"` line in the _importmap.rb_ file, then [manually doing stuff](https://stimulus.hotwired.dev/handbook/installing#using-other-build-systems), but that gave other issues that seemed like a worse path to start debugging.

**Comment by wbugenis** [comment]
I'm also running into this issue when using `lazyLoadControllersFrom`, has anyone figured this out yet? I've gotten around it by using `eagerLoadControllersFrom` instead, but this obviously isn't ideal, since it loads all of the stimulus controllers everywhere across my app...

**Comment by dhh** [comment]
Unable to replicate this using latest everything. On a fresh Rails app, I uncomment:

```javascript
import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"
lazyLoadControllersFrom("controllers", application)
```

Then add `<div data-controller="hello"></div>` to a template, which picks up `app/javascript/controllers/hello_controller.js`.

The importmap is the default:

```ruby
# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
```

Try `./bin/importmap json` to see that your controller is correctly mapped.
