### ISSUE TITLE
Autoloader eats errors

### ISSUE THREAD

**Issue by woahdae** [hotwired/stimulus-rails#12]
Since work is currently being done on the autoloader (#3, #11) I thought I'd ask - any interest in letting autoloader errors just happen?

The autoloader transforms import errors into a "Failed to autoload controller: ..." message. While writing a stimulus controller, I made a `SyntaxError` by importing a wrong module name, and had to stick a debugger into [the catch statement](https://github.com/hotwired/stimulus-rails/blob/83d678e71dd6562263ba5f219f14fe4a22e59d64/app/assets/javascripts/stimulus/loaders/autoloader.js#L14) to dig it out.

IMHO if something fails to load, swallowing the error a) confuses development, and b) will almost certainly break something downstream anyways unless your controller was entirely cruft.

At the minimum, it should console.log the error, no?

**Comment by mgodwin** [comment]
I was bitten by this as well - I think a fix could be as easy as `console.log(`Failed to autoload controller: ${controllerName}`, error)`.

**Comment by dhh** [comment]
Agree we should add a console log error.

**Comment by dhh** [comment]
Fixed in f551af04daf7e1e9d79765142423b778deea14fb
