### ISSUE TITLE
Is `hello_controller.js` necessary during install?

### ISSUE THREAD

**Issue by joshuay03** [hotwired/stimulus-rails#146]
When creating a new rails app with the default setup, `stimulus:install` adds a dummy `hello_controller.js` [here](https://github.com/hotwired/stimulus-rails/blob/96ae4e835af18d4f7eacc73fc7bfa1267bff0bcb/lib/install/stimulus_with_importmap.rb#L7-L8), which in my experience eventually just ends up getting deleted since it isn't referenced in any of the new app's view templates for demoing purposes.

Seeing as the `turbo:install` step doesn't create any dummy controllers and view templates that utilize frames, streams etc., nor any stimulus, and it's up to the user to read the handbook and figure it out for themselves, can we assume the same for stimulus controllers and drop this file? The [controller](https://github.com/hotwired/stimulus-rails/blob/main/lib/install/app/javascript/controllers/hello_controller.js) is pretty basic anyway and not really a preview of all the available stimulus APIs.

I'm happy to get a PR up to remove it if needed.

**Comment by dhh** [comment]
Yeah, we can delete it. Do a PR 👍

**Comment by joshuay03** [comment]
https://github.com/hotwired/stimulus-rails/pull/147
