### ISSUE TITLE
rails stimulus:manifest:update - change path

### ISSUE THREAD

**Issue by alec-c4** [hotwired/stimulus-rails#148]
Hey!
I use vite-rails instead of esbuild/importmaps and my JS code is located in app/frontend. I'd like to ask you - is it a good idea to add ability to move path to external config? Any idea which config file should I use to store this value?

https://github.com/hotwired/stimulus-rails/blob/96ae4e835af18d4f7eacc73fc7bfa1267bff0bcb/lib/tasks/stimulus_tasks.rake#L56

**Comment by dhh** [comment]
I would just overwrite that task entirely. Very little code in it.
