### ISSUE TITLE
Why rack-mini-profiler is being commented by the install?

### ISSUE THREAD

**Issue by fidalgo** [hotwired/stimulus-rails#26]
By checking the install for the asset pipeline, I've seen the rack-mini-profiler is being commented, but I failed to understand why?
If there is any compatibility issue, can we provide more information so it can be worked out?

Source code: https://github.com/hotwired/stimulus-rails/blob/main/lib/install/stimulus_with_asset_pipeline.rb#L22

Note: I've checked the rack-mini-profiler repo for any info and also did not found anything.

**Comment by dhh** [comment]
That mini profiler interferes with analyzing JavaScripts loads and etags, and I no longer think it should be on by default. We'll make it opt-in in Rails 7, and then we can remove this from the installer.
