### ISSUE TITLE
Mutation observer does not autoload controllers

### ISSUE THREAD

**Issue by jmalcic** [hotwired/stimulus-rails#27]
This issue to to (re)report problems autoloading `turbo-frame` content  (#14), and also to report problems with autoloading when the `data-controller` attribute of an element changes. This seems to indicate the mutation observer introduced in #11 isn't actually handling the changes it's supposed to.
### Autoloading given `turbo-frame` content
When `turbo-frame` content is loaded, new nodes are added. For a mutation observer to pick up these changes, the observer needs to be able to handle changes to the child list (the option to watch attributes only applies to existing nodes, not added/removed ones). The problem is that the [MutationRecord](http://developer.mozilla.org/en-US/docs/Web/API/MutationRecord) passed to a MutationObserver's callback has different properties depending on the type of mutation. That was the reason for [this switch](https://github.com/jmalcic/stimulus-rails/blob/1a45c6c1132c036d3952814eb67a8202cebecad5/app/assets/javascripts/stimulus/loaders/autoloader.js#L33) in #3 (there's also a similar example [here](http://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver)). [Currently](https://github.com/hotwired/stimulus-rails/blob/b4bfc2ae009e7c5b119fd1bb32b8ed5c6d73ea75/app/assets/javascripts/stimulus/loaders/autoloader.js#L39) though, only attribute mutation events are handled properly in the callback itself—not child list mutation events. You can replicate this quickly by adding puma temporarily to the Gemfile and running the dummy app, then adding a node with `data-controller="hello"`.
### Autoloading given `data-controller` attribute changes 
The mutation observer callback currently calls [this function](https://github.com/hotwired/stimulus-rails/blob/b4bfc2ae009e7c5b119fd1bb32b8ed5c6d73ea75/app/assets/javascripts/stimulus/loaders/autoloader.js#L12), passing the element whose `data-controller` attribute has changed, but because `Element.querySelectorAll()` finds descendants of the element which match the selector, this doesn't return the element with the `data-controller` attribute, so nothing gets loaded. To replicate this, do the same as above, but instead change one of the existing nodes' `data-controller` attributes to `hello`.
<hr>
There were tests in #3 to catch both of these cases (that was actually how I found out I needed to modify the callback for child list mutations). I know there's been <a href ="https://github.com/hotwired/stimulus-rails/pull/3#issuecomment-752171331">disagreement</a> about, e.g., the relative value of unit testing, and I know that there's a plan to effectively upstream the autoloader (and rewrite it in the process)—I'm not dead set on any particular approach, but I do think we need to have some tests to make sure things actually work, even if these become redundant once stimulus gets the autoloader.

**Comment by seanpdoyle** [comment]
@jmalcic thank you for re-raising this issue. I've opened https://github.com/hotwired/stimulus-rails/pull/28 to add some System Tests covering eager-, attribute-, and childList-triggered controller loading. I've cribbed the implementation details you've mentioned from #3 and have you listed as a commit co-author.
