### ISSUE TITLE
Getting Uncaught Error: Cannot find module 'controllers'

### ISSUE THREAD

**Issue by guizero** [hotwired/stimulus-rails#33]
Hello there, I have just installed Hotwire gem and everything is working fine with turbo, but I could not manage to make stimulus work.

I am getting: `Uncaught Error: Cannot find module 'controllers'`

I am using:
Rails 6.0.3.4
Ruby 2.7.1
Stimulus-rails 0.2.2

This is my application.js
```
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.

require("@rails/ujs").start()
require("@rails/activestorage").start()
require("channels")


// Uncomment to copy all static images under ../images to the output folder and reference
// them with the image_pack_tag helper in views (e.g <%= image_pack_tag 'rails.png' %>)
// or the `imagePath` JavaScript helper below.
//
// const images = require.context('../images', true)
// const imagePath = (name) => images(name, true)

import "controllers"

require("trix")
require("@rails/actiontext")
```

I have tried running `rails stimulus:install` 

The error I get is:
```
Uncaught Error: Cannot find module 'controllers'
    at webpackMissingModule
```

**Comment by jacobdaddario** [comment]
Is there a controllers directory anywhere in your application? It may be that Stimulus was installed into the asset pipeline, meaning that the controllers folder is in yours `app/assets` folder. I believe that the error is saying that Webpack can't find the controllers folder in its load path.

**Comment by guizero** [comment]
Hey @jacobdaddario . Yes, the javascripts/controllers is there with the hello_world_controller.js 

I believe that the imported controllers was coming from this gem. Do I have to create a controllers/index.js manually?

**Comment by guizero** [comment]
Just so you understand the steps I have followed.

Using Rails 6.1.1.1

```
rails new app
cd app
bundle install
bundle add hotwire-rails
rails hotwire:install
```

And then scaffolded a posts model. Just that

When visiting localhost:3000/posts the error shows up

**Comment by kuei0221** [comment]
I have encountered the same problem and find the solution in [hotwire's document](https://stimulus.hotwire.dev/handbook/installing)
The path has modified to fit the directory hotwire auto-created.
```
import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"

const application = Application.start()
const context = require.context("../controllers", true, /\.js$/)
application.load(definitionsFromContext(context))
```

**Comment by guizero** [comment]
Hey @kuei0221 , cool! I'd done the same to make it work. I just believe that this should be added to this gem, I mean, when using webpacker (currently default on rails apps) this index should be created as well.

Actually, when you run 
rails webpacker:install:stimulus

The file is created.

**Comment by kuei0221** [comment]
Cool, that is what exactly we need. I found this file here https://github.com/rails/webpacker/blob/v4.0.0/lib/install/examples/stimulus/controllers/index.js,
we can just place it in the controller directory and `stimulus:install:webpacker` will handle it for us.
I will make a PR for this 😄

**Comment by guizero** [comment]
I am happy to see that it was already merged =) @kuei0221

**Comment by afomera** [comment]
Ran into this issue when I added hotwire-rails and then ran the install script, Appears fixed in `main` from when using stimulus-rails from GitHub. Hoping @dhh or friends can ship a new release soon so we don't need to use the gem from GitHub (and so hotwire-rails's gem will just work) 🤞

**Comment by noctivityinc** [comment]
The README needs to be updated to reflect the new steps
