### ISSUE TITLE
Autoloading race conditions

### ISSUE THREAD

**Issue by mgodwin** [hotwired/stimulus-rails#35]
I love the autoloader in conjunction with native ESM modules, but I'm running into a race condition that I suspect others will bump into.

In my project I have a canvas that is controlled by a stimulus controller - it allows you to draw on it when clicked.

When I run my capybara system tests, it's not difficult to have the tests fail because the stimulus controller attached to the canvas hasn't yet been loaded.  Of course, this problem is pronounced in an automated testing scenario, but given different network conditions, it's not unreasonable to think it could pop up for regular usage situations as well.

I previously solved this problem by eager loading all my stimulus controllers, and suspect that's what I'll end up doing to work around this in the short-term.  I'm curious what other thoughts there may be around how to handle this.  

In this case, if there were some way to show a message/loading indicator on the canvas, that could help prevent issues of interacting before the stimulus controller had loaded, but I feel like that's not going to be generic enough to apply to every situation.  My other thought is maybe to have the autoloader dispatch an event when a controller loads that you could listen to, but I don't love how manual that'd be.

For anyone else that's struggling with this, here's my code that allows you to eager load using native ESM:

```js
  <%= javascript_include_tag("stimulus/libraries/es-module-shims", type: "module") %>
  <%= tag.script(type: "importmap-shim", src: asset_path("importmap.json")) %>
  <%= javascript_include_tag("turbo", type: "module-shim") %>
  <%= javascript_include_tag("stimulus/libraries/stimulus", type: "module-shim") %>
  <script type="module-shim" type=text/javascript>
    import { Application } from 'stimulus'

    const application = Application.start()
    <% controllers = Rails.root.join('app/assets/javascripts/controllers').children.map { |filename| filename.basename.to_s.remove(filename.extname).split('_controller').first } %>
    const controllerNames = <%= controllers.to_json.html_safe %>
    controllerNames.forEach((controllerName) => {
      let controllerFilename = `${controllerName}_controller`

      import(controllerFilename).then((controllerModule) => {
        application.register(controllerName.replace('_', '-'), controllerModule.default)
      }).catch(error => console.log(`Failed to autoload controller: ${controllerName}`, error))
    })
  </script>
```

Of course, you can always just use webpacker and bundle it all together for an easy eager-loading solution too.

**Comment by dhh** [comment]
All import map loading is done as deferred. Best way is to prepare your HTML in such a way that it shows a spinner, then when the controller is active, you can replace that.

**Comment by seanpdoyle** [comment]
I mentioned it in https://github.com/hotwired/stimulus-rails/pull/49/files#r610601520, but would it be viable for the autoloader to mark elements with a `[data-stimulus-autoloading="..."]` attribute, or something like it? That way extensions to Capybara could be prefixed with something like `assert_no_css "[data-stimulus-autoloading]"` before interacting with the page.

While I think spinners or loading indicators can improve end-user experience, they might not make sense for all elements on a page.

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/stimulus-rails/pull/57 to more concretely illustrate my proposal.

It's a draft PR, since there are still some points worth discussing.
