### ISSUE TITLE
Controllers are connected multiple times

### ISSUE THREAD

**Issue by mrhead** [hotwired/stimulus-rails#4]
When I have just one element with a controller, then everything works as expected and the controller gets connected just once. However, when I have n elements with the same controller, then each element is connected n times.

This can be reproduced with the following controller:

```js
// app/assets/javascripts/controllers/hello_controller.js
import { Controller } from "stimulus"

export default class extends Controller {
  connect() {
    this.element.textContent = "Hello World!"
    console.log(this.element)
  }
}
```

It looks like this with two elements with `data-controller="hello"`:

https://user-images.githubusercontent.com/522375/103111075-4b035a80-4649-11eb-8ec1-a372bb27ab00.mov

**Comment by woahdae** [comment]
I might be experiencing the same issue in a slightly different way. I'm working my way through the [demo chat app](https://github.com/hotwired/hotwire-rails-demo-chat), and added a `messages` stimulus controller to the `#messages` div. On initial page load the controller is loaded once, but when adding a new message via the input in the `new_message` frame, the controller is re-connected twice.

I can make a better repro if needed, but I thought I'd jump in while motivated.
