### ISSUE TITLE
Release the latest version

### ISSUE THREAD

**Issue by dixpac** [hotwired/stimulus-rails#46]
@dhh can you release the latest version 🙏🏼 🙏🏼 
Current release `0.2.2` doesn't work with webpacker since it is missing [the definitions](https://github.com/hotwired/stimulus-rails/blob/main/lib/install/app/assets/javascripts/controllers/index.js)
(works from the the master, but... 😄 )

**Comment by dhh** [comment]
0.2.3 is out ✌️
