### ISSUE TITLE
Fails when used in project with no sprockets

### ISSUE THREAD

**Issue by coder2000** [hotwired/stimulus-rails#48]
I have a new project configured with webpacker and no sprockets. Stimulus rails fails to load as it is looking for a configuration option that is not available.

**Comment by sandrasi** [comment]
It not only fails to load but it pretty much breaks all other rails commands, like `$ rails generate migration`. The offending code is in engine.rb which only works with the Sprockets asset pipeline.

**Comment by coder2000** [comment]
I understand that it is not hard to set up stimulus manually with webpacker but when you are using hotwire-rails which includes this gem it should fail gracefully as not everyone may know where the error is coming from.

**Comment by dhh** [comment]
Feel free to open a PR that addresses this 👍
