### ISSUE TITLE
Error while running `hotwire:install`, which itself runs `stimulus:install`

### ISSUE THREAD

**Issue by dmarcoux** [hotwired/stimulus-rails#55]
### Description

After adding the gem `hotwire-rails` to my Gemfile and running `bundle exec rails hotwire:install`, I get the following output containing an error (`Errno::ENOENT: No such file or directory - bin/bundle`):

> Copying Stimulus JavaScript
>       create  app/assets/javascripts
>       create  app/assets/javascripts/controllers/hello_controller.js
>       create  app/assets/javascripts/controllers/index.js
>       create  app/assets/javascripts/importmap.json.erb
>       create  app/assets/javascripts/libraries
>       create  app/assets/javascripts/libraries/.keep
> Add app/assets/javascripts to asset pipeline manifest
>       append  app/assets/config/manifest.js
> Add Stimulus include tags in application layout
>       insert  app/views/layouts/application.html.erb
> Turn off development debug mode
>         gsub  config/environments/development.rb
> Turn off rack-mini-profiler
>         gsub  Gemfile
>          run  bin/bundle from "."
> rails aborted!
> Errno::ENOENT: No such file or directory - bin/bundle
> /app/bin/rails:5:in `<top (required)>'
> /app/bin/spring:10:in `require'
> /app/bin/spring:10:in `block in <top (required)>'
> /app/bin/spring:7:in `<top (required)>'
> Tasks: TOP => app:template
> (See full trace by running task with --trace)
> Yield head in application layout for cache helper
>       insert  app/views/layouts/application.html.erb
> Add Turbo include tags in application layout
>       insert  app/views/layouts/application.html.erb
> Add Turbo to importmap
>       insert  app/assets/javascripts/importmap.json.erb
> Enable redis in bundle
>         gsub  Gemfile
> Switch development cable to use redis
>         gsub  config/cable.yml
> Turbo successfully installed ⚡️

### Steps to Reproduce

1. Create a new Rails app with `rails new app123 --skip-javascript` and add `hotwire-rails` gem to the Gemfile.
2. Run `bundle && bundle exec rails hotwire:install`
3. See the error

### Workaround

Running `bundle binstubs bundler` creates the missing `bin/bundle` in my project. I guess the rake task `stimulus:install` shouldn't assume that `bin/bundle` is present. This is the line which is causing the issue: https://github.com/hotwired/stimulus-rails/blob/7e44ddcb39e1e9a2564733a2b850cf012e2ac819/lib/install/stimulus_with_asset_pipeline.rb#L23

**Comment by dhh** [comment]
Binstubs are intended to be created by default on new apps. If that's not happening for you, that's a Rails issue that we should find and fix. Feel free to open a ticket there.
