### ISSUE TITLE
Errors regarding es-module-shims & autoloading controllers thrown randomly

### ISSUE THREAD

**Issue by kylazath** [hotwired/stimulus-rails#62]
Hello, recently I've noticed that there are some errors thrown in the console from time to time when using Stimulus in a application that I am working on (using Rails 6 & no Webpacker).

I tried to reproduce this problem on a fresh app and it still happens.

Steps to reproduce this problem:
1. create new rails project with ```--skip-webpack-install``` and ```--skip-javascript``` to get rid of Webpacker,
2. add ```stimulus-rails``` gem,
3. create a page on which you use ```hello``` controller generated by ```rails stimulus:install```,
4. if you refresh few times you should be able to see errors like this in the console
  ![image](https://user-images.githubusercontent.com/22963604/122714383-82a13700-d267-11eb-8e96-d346fa851579.png)
  ![image](https://user-images.githubusercontent.com/22963604/122714407-8b920880-d267-11eb-8c20-861c25b35916.png)
  
Browsers on which I managed to reproduce this problem: Firefox, Firefox Nightly, Firefox Developer Edition, Opera, MS Edge, Chrome for developers.

**Comment by dhh** [comment]
Please see if you can replicate this on the new approach with importmap-rails that uses native support in Edge/Chrome and inline import maps.
