### ISSUE TITLE
stimulus:install task breaks asset compilation when using Webpacker

### ISSUE THREAD

**Issue by DavidColby** [hotwired/stimulus-rails#66]
The changes in #65 included an update to the `hello_controller` created by the install script to reference `@hotwired/stimulus` instead of `stimulus`

With this change, Webpacker users will now see the following error when they attempt to compile:

```
ERROR in ./app/javascript/controllers/hello_controller.js
Module not found: Error: Can't resolve '@hotwired/stimulus' in '/code/new-app/app/javascript/controllers'
resolve '@hotwired/stimulus' in '/code/new-app/app/javascript/controllers'
```

Steps to reproduce:

1. `rails new my-app`
2. `bundle add stimulus-rails`
3. `rails stimulus:install`
4. `bin/webpack-dev-server`

A fix for this might be using `gsub_file` after the controllers directory is copied in the Webpacker install script to replace `from "@hotwired/stimulus"` with `from "stimulus"` which I'm happy to put in a PR for if that's an acceptable path to a resolution.

**Comment by dhh** [comment]
Ah yeah. Stimulus is moving shortly to that new destination on npm, but yes, let’s do a rename in the interim.
