### ISSUE TITLE
Turn of stimulus response in Rails console.

### ISSUE THREAD

**Issue by beekimrj** [hotwired/stimulus-rails#70]
In **Rails**, Stimulus js response is visible in rails console, i.e. whole HTML page that it sends to client, I would like to turn it off as log is taking more space than it should, how can i achieve it, I couldn't find any solution
I have attached sample of  console that is being showing in rails console.
 
![stimulus](https://user-images.githubusercontent.com/22666854/131625606-f366f8dc-7a2d-4db3-8551-a7b2e6b3c767.png)

**Comment by dhh** [comment]
This is an issue for StimulusReflex. Stimulus by default doesn't send anything down the wire.
