### ISSUE TITLE
Uncaught TypeError: __require.context is not a function

### ISSUE THREAD

**Issue by noelrappin** [hotwired/stimulus-rails#73]
I get this trying to install Stimulus using the new `esbuild-rails` (which I guess has just been replaced by `jsbundling-rails`, but I think the issue holds

`Uncaught TypeError: __require.context is not a function`, it's from the `controllers/index.js` line 

```
const context = require.context("controllers", true, /_controller\.(js|ts)$/)
```

I'm not sure whether this is a case where the install is giving me the wrong thing (and I should be using the node install and importing all my files one-by-one) or whether there's a way to make the require work.

Thanks

**Comment by dhh** [comment]
The latest stimulus-rails uses a different approach to loading the controllers. Right now it's "manual", but I'm working on something better. esbuild doesn't have context, though, so the old Webpack approach won't work.

**Comment by dhh** [comment]
Basically, you can't do file-based globs at all with esbuild.

**Comment by noelrappin** [comment]
Are we eventually going to get to something like https://github.com/hotwired/stimulus-rails/pull/32?

**Comment by dhh** [comment]
Auto loading only works with import maps, and there I’m not sure it’s worth the effort. But with import maps we at least have a straight forward way to glob.
