### ISSUE TITLE
Release 0.5 busts the installer

### ISSUE THREAD

**Issue by msmiller** [hotwired/stimulus-rails#74]
Just tried installing on a new Rails 6.1 codebase. Running `./bin/rails stimulus:install` didn't install the 'controllers' directory or change application.js. Rolling back to 0.4.2 got it all working fine.

**Comment by dhh** [comment]
Stimulus 0.5+ requires the importmap-rails gem OR jsbundling-rails. The error message it gives when you try to install without this is accurate:

```base
M1A 2.7.2 ~/Work/rails/demos/current main # r stimulus:install
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
```
