### ISSUE TITLE
controller files *.js.erb silently fail (with new loader `stimulus-loading`)

### ISSUE THREAD

**Issue by adas172002** [hotwired/stimulus-rails#83]
Hello,

New loader module `stimulus-loading.js`, when used in default eager loading mode, silently fails. My setup shows only hello-controller on the list of app assets in dev console. out of 3 controller files, 2 of them are with `.erb`. When switched to lazy loading, produces warning 
```
Failed to autoload controller: output
Error: Unable to resolve specifier 'controllers/output_controller' from http://localhost:3003/assets/stimulus-loading-685d40a0b68f785d3cdbab1c0f3575320497
```
My `output_controller.jr.erb` is using erb code and worked fine before updating to new loader in 0.7.1

`importmap.rb`:
`pin_all_from "app/javascript/controllers", under: "controllers"`
sprockets `manifest.js`:
`//= link_tree ../../javascript .js`

I am not sure if this is a bug or something wrong in my app setup.

If I use `rails stimulus:manifest:update` task generated imports are using `.erb` in the import names, which is not working. But after correcting import names to end with `.js` they work.

**Comment by alanq** [comment]
Having this issue with stimulus-rails 1.0.4 and sprockets. Did you resolve this?

**Comment by adas172002** [comment]
@alanq, I do not recall the details now, it's been a while. I am sure that I had to refactor my code to avoid using `.erb` templates, as Sprockets does not recompile them to JS code.
