### ISSUE TITLE
Generated controllers/index.js doesn't seem to work in production

### ISSUE THREAD

**Issue by ianneub** [hotwired/stimulus-rails#87]
With a basic Rails 7.0.0 app, running `./bin/rails stimulus:manifest:update` will create a `app/javascript/controllers/index.js` file that doesn't seem to work in production, at least not for some people.

Changing this line:

    import { application } from "./application"

to:

    import { application } from "controllers/application"

And change each controller import from:

    import NameController from "./name_controller.js"

to:

    import NameController from "controllers/name_controller"

Seems to fix the problem in production.

Ref: https://stackoverflow.com/questions/69757938/404-errors-on-javascript-when-using-importmaps-in-rails-7-in-production

**Comment by dhh** [comment]
The import-mapped approach to this is to use the autoloader. You shouldn't be using the manifest:update with import maps. We should document this / maybe even short-circuit the command if you try.

**Comment by ianneub** [comment]
> The import-mapped approach to this is to use the autoloader. You shouldn't be using the manifest:update with import maps. We should document this / maybe even short-circuit the command if you try.

Ah I see, thank you. It looks like my issue is because of: 
https://github.com/hotwired/stimulus-rails/blob/main/lib/generators/stimulus/stimulus_generator.rb#L9

I have a `package.json` file for generating CSS. I'm not using it for the Javascript side though.

**Comment by dhh** [comment]
That's a good catch. Perhaps we should flip this detection such that it looks for the presence of config/importmap.rb instead of looking for package.json!

**Comment by ianneub** [comment]
Maybe something like #89 @dhh ? I can take a stab at the docs as well before merging.

**Comment by ianneub** [comment]
Looking at the README, it may not be necessary to explicitly mention that the `stimulus:manifest:update` task is not needed. Speaking for myself, I probably wouldn't have tried to use the command if the generated file hadn't mentioned it.
